language: python
python:
    - "2.7"
compiler:
    - gcc

before_install:
# Install miniconda to avoid compiling scipy
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -q -n pyenv mkl python=2.7 numpy=1.6.2 scipy=0.11 nose=1.1 pyparsing=1.5 pip flake8==2.3
    - source activate pyenv
    - pip install pydot
    - pip install theano
    - echo "[gcc] " > ~/.theanorc
    - echo "cxxflags = -march=x86-64" >> ~/.theanorc

script:
    - python -c 'import theano'
