language: python
python:
    - "2.7"
compiler:
    - gcc

install:
    - pip install theano
    - echo "[gcc] " > ~/.theanorc
    - echo "cxxflags = -march=x86-64" >> ~/.theanorc

script:
    - python -c 'import theano'
